### ISSUE TITLE
RejectedExecutionException

### ISSUE THREAD

**Issue by colin-scott** [NetSys/sts2-interposition#101]
Found after lots of fuzzing:

```
Returned to main with events
Restarting system
Shutting down the actor system. 6
Exception in thread "main" java.util.concurrent.RejectedExecutionException: Must be called prior to system shutdown.
        at akka.actor.ActorSystemImpl$TerminationCallbacks.add(ActorSystem.scala:795)
        at akka.actor.ActorSystemImpl.registerOnTermination(ActorSystem.scala:641)
        at akka.actor.ActorSystemImpl.registerOnTermination(ActorSystem.scala:640)
        at akka.dispatch.verification.Instrumenter$$anonfun$shutdown_system$4.apply(Instrumenter.scala:481)
        at akka.dispatch.verification.Instrumenter$$anonfun$shutdown_system$4.apply(Instrumenter.scala:478)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
        at akka.dispatch.verification.Instrumenter.shutdown_system(Instrumenter.scala:478)
        at akka.dispatch.verification.Instrumenter.restart_system(Instrumenter.scala:493)
        at akka.dispatch.verification.ExternalEventInjector$class.handle_shutdown(ExternalEventInjector.scala:561)
        at akka.dispatch.verification.RandomScheduler.handle_shutdown(RandomScheduler.scala:41)
        at akka.dispatch.verification.RandomScheduler.shutdown(RandomScheduler.scala:480)
        at akka.dispatch.verification.RunnerUtils$.fuzz(RunnerUtils.scala:54)
        at Main$.delayedEndpoint$Main$1(Runner.scala:189)
        at Main$delayedInit$body.apply(Runner.scala:133)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at Main$.main(Runner.scala:133)
        at Main.main(Runner.scala)
```

**Comment by colin-scott** [comment]
Ah, this was because the disk ran out of space
