### ISSUE TITLE
RandomScheduler crash

### ISSUE THREAD

**Issue by colin-scott** [NetSys/sts2-interposition#81]
Just documenting a few crashes I've observed. This one, in RandomScheduler.scala during fuzz testing:

RandomScheduler?

```
Checking invariant
handleTick Actor[akka://new-system-0/user/raft-member-6#246399049]
handleTick Actor[akka://new-system-0/user/raft-member-7#-548325259]
[ERROR] [03/01/2015 18:35:51.006] [new-system-0-akka.actor.default-dispatcher-10] [akka://new-system-0/user/raft-member-9] null
java.util.NoSuchElementException
        at scala.collection.mutable.LinkedListLike$class.head(LinkedListLike.scala:75)
        at scala.collection.mutable.LinkedList.head(LinkedList.scala:80)
        at scala.collection.mutable.MutableList.head(MutableList.scala:53)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.mutable.MutableList.foreach(MutableList.scala:29)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
        at akka.dispatch.verification.ExternalEventInjector$class.send_external_messages(ExternalEventInjector.scala:130)
        at akka.dispatch.verification.RandomScheduler.send_external_messages(RandomScheduler.scala:32)
        at akka.dispatch.verification.ExternalEventInjector$class.send_external_messages(ExternalEventInjector.scala:114)
        at akka.dispatch.verification.RandomScheduler.send_external_messages(RandomScheduler.scala:32)
        at akka.dispatch.verification.RandomScheduler.schedule_new_message(RandomScheduler.scala:238)
        at akka.dispatch.verification.Instrumenter.afterMessageReceive(Instrumenter.scala:249)
        at sample.WeaveActor.ajc$after$sample_WeaveActor$3$79e3ab71(WeaveActor.aj:52)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by colin-scott** [comment]
Another NoSuchElementException:

```
[info] java.lang.IllegalArgumentException: No such element (Uniq((akka.actor.ActorCell@100f9bbe,Envelope(CompletionEvent(ResultTask(0, 0),Success,Some(78783),null,org.apache.spar
k.scheduler.TaskInfo@619eb702,org.apache.spark.executor.TaskMetrics@5b4302ac),Actor[akka://new-system-1/deadLetters])),54),Unique(MsgEvent(deadLetters,$a,BasicFingerprint(Complet
ionEvent(ResultTask(0, 0),Success,Some(78783),null,org.apache.spark.scheduler.TaskInfo@619eb702,org.apache.spark.executor.TaskMetrics@5b4302ac))),56))
[info]  at akka.dispatch.verification.MultiSet.$minus$eq(Util.scala:72) ~[classes/:na]
[info]  at akka.dispatch.verification.RandomizedHashSet.remove(Util.scala:139) ~[classes/:na]
[info]  at akka.dispatch.verification.RandomizedHashSet.removeRandomElement(Util.scala:151) ~[classes/:na]
[info]  at akka.dispatch.verification.RandomScheduler$$anonfun$7.apply(RandomScheduler.scala:400) ~[classes/:na]
[info]  at akka.dispatch.verification.RandomScheduler$$anonfun$7.apply(RandomScheduler.scala:400) ~[classes/:na]
[info]  at akka.dispatch.verification.Util$.find_non_blocked_message(Util.scala:424) ~[classes/:na]
[info]  at akka.dispatch.verification.RandomScheduler.schedule_new_message(RandomScheduler.scala:397) ~[classes/:na]
[info]  at akka.dispatch.verification.Instrumenter.afterMessageReceive(Instrumenter.scala:422) ~[classes/:na]
[info]  at sample.WeaveActor.ajc$after$sample_WeaveActor$2$79e3ab71(WeaveActor.aj:56) ~[classes/:na]
[info]  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498) [classes/:na]
[info]  at akka.actor.ActorCell.invoke(ActorCell.scala:456) [classes/:na]
[info]  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237) [classes/:na]
[info]  at akka.dispatch.Mailbox.run(Mailbox.scala:219) [classes/:na]
[info]  at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) [classes/:na]
[info]  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
[info]  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
[info]  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
[info]  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
```
