### ISSUE TITLE
Another, different crash in DPORwHeuristics

### ISSUE THREAD

**Issue by colin-scott** [NetSys/sts2-interposition#86]
in isCoEnabled:

```
Computing backtrack points. This may take awhile...
[ERROR] [04/02/2015 14:37:26.201] [new-system-22-akka.actor.default-dispatcher-3] [akka://new-system-22/user/raft-member-7] None.get
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:322)
        at scala.None$.get(Option.scala:320)
        at akka.dispatch.verification.DPORwHeuristics.akka$dispatch$verification$DPORwHeuristics$$isCoEnabeled$1(DPORwHeuristics.scala:1296)
        at akka.dispatch.verification.DPORwHeuristics$$anonfun$dpor$1$$anonfun$apply$mcVI$sp$1.apply$mcVI$sp(DPORwHeuristics.scala:1326)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at akka.dispatch.verification.DPORwHeuristics$$anonfun$dpor$1.apply$mcVI$sp(DPORwHeuristics.scala:1323)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
        at akka.dispatch.verification.DPORwHeuristics.dpor(DPORwHeuristics.scala:1320)
        at akka.dispatch.verification.DPORwHeuristics.notify_quiescence(DPORwHeuristics.scala:1060)
        at akka.dispatch.verification.Instrumenter.afterMessageReceive(Instrumenter.scala:267)
        at sample.WeaveActor.ajc$after$sample_WeaveActor$3$79e3ab71(WeaveActor.aj:53)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by colin-scott** [comment]
Maybe another one?

```
java.util.NoSuchElementException
        at scalax.collection.immutable.AdjacencyListBase$NodeSet$class.get(AdjacencyListBase.scala:232)
        at scalax.collection.mutable.AdjacencyListGraph$NodeSet.get(AdjacencyListGraph.scala:74)
        at scalax.collection.mutable.AdjacencyListGraph$NodeSet.get(AdjacencyListGraph.scala:74)
        at scalax.collection.GraphLike$class.get(Graph.scala:234)
        at scalax.collection.mutable.DefaultGraphImpl.get(Graph.scala:263)
        at akka.dispatch.verification.DPORwHeuristics.getMessage(DPORwHeuristics.scala:894)
        at akka.dispatch.verification.DPORwHeuristics.event_produced(DPORwHeuristics.scala:929)
        at akka.dispatch.verification.Instrumenter.aroundDispatch(Instrumenter.scala:915)
        at akka.dispatch.Dispatcher.dispatch_aroundBody1$advice(Dispatcher.scala:73)
        at akka.dispatch.Dispatcher.dispatch(Dispatcher.scala:1)
        at akka.actor.dungeon.Dispatch$class.sendMessage(Dispatch.scala:123)
        at akka.actor.ActorCell.sendMessage(ActorCell.scala:369)
        at akka.actor.Cell$class.sendMessage(ActorCell.scala:290)
        at akka.actor.ActorCell.sendMessage(ActorCell.scala:369)
        at akka.actor.RepointableActorRef.$bang_aroundBody0(RepointableActorRef.scala:166)
        at akka.actor.RepointableActorRef.$bang_aroundBody1$advice(RepointableActorRef.scala:180)
        at akka.actor.RepointableActorRef.$bang(RepointableActorRef.scala:1)
        at pl.project13.scala.akka.raft.Leader$$anonfun$replicateLog$1.apply(Leader.scala:139)
        at pl.project13.scala.akka.raft.Leader$$anonfun$replicateLog$1.apply(Leader.scala:135)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at pl.project13.scala.akka.raft.Leader$class.replicateLog(Leader.scala:135)
        at pl.project13.scala.akka.raft.RaftActor.replicateLog(RaftActor.scala:14)
        at pl.project13.scala.akka.raft.Leader$class.sendHeartbeat(Leader.scala:131)
        at pl.project13.scala.akka.raft.RaftActor.sendHeartbeat(RaftActor.scala:14)
        at pl.project13.scala.akka.raft.Leader$$anonfun$1.applyOrElse(Leader.scala:27)
        at pl.project13.scala.akka.raft.Leader$$anonfun$1.applyOrElse(Leader.scala:19)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
        at akka.actor.FSM$class.processEvent(FSM.scala:604)
        at pl.project13.scala.akka.raft.RaftActor.akka$actor$LoggingFSM$$super$processEvent(RaftActor.scala:14)
        at akka.actor.LoggingFSM$class.processEvent(FSM.scala:734)
        at pl.project13.scala.akka.raft.RaftActor.processEvent(RaftActor.scala:14)
        at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
        at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:570)
```
