### ISSUE TITLE
crash: not all shrinkable_sends the same,  branch: akka-raft

### ISSUE THREAD

**Issue by colin-scott** [NetSys/sts2-interposition#91]
```
shrinkable_sends: List(Send(raft-member-1,BootstrapMessageConstructor(Set())), Send(raft-member-2,BootstrapMessageConstructor(Set())), Send(raft-member-3,BootstrapMessageConstructor(Set())), Send(raft-member-4,BootstrapMessageConstructor(Set())), Send(raft-member-5,BootstrapMessageConstructor(Set())), Send(raft-member-6,BootstrapMessageConstructor(Set())), Send(raft-member-7,BootstrapMessageConstructor(Set())))
Exception in thread "main" java.lang.IllegalArgumentException: Not all shrinkable_sends the same
        at akka.dispatch.verification.RunnerUtils$.shrinkSendContents(RunnerUtils.scala:557)
        at Main$$anonfun$9.apply(Runner.scala:189)
        at Main$$anonfun$9.apply(Runner.scala:186)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at Main$.delayedEndpoint$Main$1(Runner.scala:186)
        at Main$delayedInit$body.apply(Runner.scala:120)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at Main$.main(Runner.scala:120)
        at Main.main(Runner.scala)
```

**Comment by colin-scott** [comment]
Shouldn't happen!
